a = input('Digite algo: ')
print('P tipo primitivo valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alvafanumero? ', a.isalnum())
print('esta em Maiusculas? ', a.isupper())
print('esta em Minusculas? ', a.islower())
print('esta Capitalizada? ', a.istitle())